[docs] sql 파일 추가
depromeet/13th-1team-backend pull request #186
Opened 2023-06-16 04:56 UTC by likelasttime

## 개요
- close #185 

## 작업사항
- 도메인 모듈에 sql 파일 추가

2023-06-16 11:20 UTC, jjddhh approved these changes

2023-06-16 11:20 UTC, jjddhh commented on Module-Domain/src/main/resources/data.sql
해당 부분들 pk값 설정해주어야 하지 않을까요??

2023-06-16 11:20 UTC, jjddhh commented
어디선가 충돌이 났나보네요~

2023-06-17 09:37 UTC, likelasttime commented on Module-Domain/src/main/resources/data.sql
H2 데이터베이스 콘솔에서 직접 쿼리 날렸는데 문제없었어요

2023-06-17 10:54 UTC, jjddhh requested changes

2023-06-17 10:54 UTC, jjddhh commented on Module-Domain/src/main/resources/data.sql
네 문제는 없을텐데 pk값은 설정해주시는게 좋을것 같아요~

2023-06-18 00:16 UTC, jjddhh commented on Module-Domain/src/main/resources/data.sql
아 문제없다는게 문제없이 pk 값이 들어간다는 의미였군요. 확인했습니다~
현재 카테고리 테이블의 pk 컬럼명이 id인데 이 부분만 category_id로 변경되게끔 해주시면 될거 같아요~

2023-06-18 00:17 UTC, jjddhh commented
해당 테스트 실패 오류는 아직인걸까요?

2023-06-18 02:36 UTC, closed without merging